# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.srcs/sources_1/ip/fifo_dual/fifo_dual.xci
# IP: The module: 'fifo_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/fifo_dual/fifo_dual.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/fifo_dual/fifo_dual_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/fifo_dual/fifo_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.srcs/sources_1/ip/fifo_dual/fifo_dual.xci
# IP: The module: 'fifo_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/fifo_dual/fifo_dual.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/fifo_dual/fifo_dual_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/fifo_dual/fifo_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
