# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sram_controller.xdc

# IP: ip/ila_sram_ctrl/ila_sram_ctrl.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_sram_ctrl || ORIG_REF_NAME==ila_sram_ctrl} -quiet] -quiet
