# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.srcs/sources_1/ip/mmcm_120mhz/mmcm_120mhz.xci
# IP: The module: 'mmcm_120mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/mmcm_120mhz/mmcm_120mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_120mhz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/mmcm_120mhz/mmcm_120mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_120mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/mmcm_120mhz/mmcm_120mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_120mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.srcs/sources_1/ip/mmcm_120mhz/mmcm_120mhz.xci
# IP: The module: 'mmcm_120mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/mmcm_120mhz/mmcm_120mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_120mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/mmcm_120mhz/mmcm_120mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_120mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week3/week3/week3.gen/sources_1/ip/mmcm_120mhz/mmcm_120mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_120mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
