set_property PACKAGE_PIN L17 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports cs_n]
set_property PACKAGE_PIN T1 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF]

set_property PACKAGE_PIN R3 [get_ports sck]
set_property PACKAGE_PIN T3 [get_ports mosi]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_ila]
