set_property PACKAGE_PIN G2 [get_ports {in[1]}]
set_property PACKAGE_PIN G3 [get_ports {in[0]}]
set_property PACKAGE_PIN G1 [get_ports {in[2]}]
set_property PACKAGE_PIN G4 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports out]
