# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard.xci
# IP: The module: 'pll_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wizard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard.xci
# IP: The module: 'pll_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/week3/week3.srcs/sources_1/ip/pll_wizard/pll_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
