# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.srcs/sources_1/ip/mmcm_rx/mmcm_rx.xci
# IP: The module: 'mmcm_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.srcs/sources_1/ip/mmcm_rx/mmcm_rx.xci
# IP: The module: 'mmcm_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/mmcm_rx/mmcm_rx_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
