# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.srcs/sources_1/ip/ila_rgb_gray/ila_rgb_gray.xci
# IP: The module: 'ila_rgb_gray' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/ila_rgb_gray/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rgb_gray'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/ila_rgb_gray/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rgb_gray'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/ila_rgb_gray/ila_rgb_gray_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rgb_gray'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.srcs/sources_1/ip/ila_rgb_gray/ila_rgb_gray.xci
# IP: The module: 'ila_rgb_gray' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/ila_rgb_gray/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rgb_gray'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/ila_rgb_gray/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rgb_gray'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week5/Week5/Week5.gen/sources_1/ip/ila_rgb_gray/ila_rgb_gray_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_rgb_gray'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
