set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports osc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports yellow]
set_property PACKAGE_PIN L17 [get_ports osc_clk]
set_property PACKAGE_PIN A14 [get_ports green]
set_property PACKAGE_PIN A15 [get_ports red]
set_property PACKAGE_PIN C15 [get_ports yellow]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
