# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.srcs/sources_1/ip/mmcm_uart/mmcm_uart.xci
# IP: The module: 'mmcm_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.gen/sources_1/ip/mmcm_uart/mmcm_uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_uart'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.gen/sources_1/ip/mmcm_uart/mmcm_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.gen/sources_1/ip/mmcm_uart/mmcm_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.srcs/sources_1/ip/mmcm_uart/mmcm_uart.xci
# IP: The module: 'mmcm_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.gen/sources_1/ip/mmcm_uart/mmcm_uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.gen/sources_1/ip/mmcm_uart/mmcm_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week3/week3/week3.gen/sources_1/ip/mmcm_uart/mmcm_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
