# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.srcs/sources_1/ip/mmcm_cdc/mmcm_cdc.xci
# IP: The module: 'mmcm_cdc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.gen/sources_1/ip/mmcm_cdc/mmcm_cdc_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_cdc'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.gen/sources_1/ip/mmcm_cdc/mmcm_cdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_cdc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.gen/sources_1/ip/mmcm_cdc/mmcm_cdc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_cdc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.srcs/sources_1/ip/mmcm_cdc/mmcm_cdc.xci
# IP: The module: 'mmcm_cdc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.gen/sources_1/ip/mmcm_cdc/mmcm_cdc_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_cdc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.gen/sources_1/ip/mmcm_cdc/mmcm_cdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_cdc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.gen/sources_1/ip/mmcm_cdc/mmcm_cdc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_cdc'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
