# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.srcs/sources_1/ip/mmcm_spi/mmcm_spi.xci
# IP: The module: 'mmcm_spi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.gen/sources_1/ip/mmcm_spi/mmcm_spi_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_spi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.gen/sources_1/ip/mmcm_spi/mmcm_spi.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.gen/sources_1/ip/mmcm_spi/mmcm_spi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.srcs/sources_1/ip/mmcm_spi/mmcm_spi.xci
# IP: The module: 'mmcm_spi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.gen/sources_1/ip/mmcm_spi/mmcm_spi_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.gen/sources_1/ip/mmcm_spi/mmcm_spi.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/Reference/Week4/week4/week4.gen/sources_1/ip/mmcm_spi/mmcm_spi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
