set_property SRC_FILE_INFO {cfile:{C:/Users/Jihoon Lee/Desktop/commento/commento_fpga_material/LiveClass/week5/week5/week5.srcs/constrs_1/new/cdc_2ff.xdc} rfile:../../../week5.srcs/constrs_1/new/cdc_2ff.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U10 [get_ports clk]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U11 [get_ports din]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports dout]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U13 [get_ports rst_n]
